backend:
  name: git-gateway
  branch: master
media_folder: "media"
public_folder: "media"
publish_mode: editorial_workflow
collections:
  - label: "About"
    name: "about"
    files:
      - label: "About"
        name: "info"
        format: "json"
        file: "content/about.json"
        fields:
          - { label: "Message", name: message, widget: string }
